package yasdb

import (
	"fmt"
	"strings"

	"github.com/emirpasic/gods/sets/hashset"
	"github.com/thoas/go-funk"
)

// ReservedWordsList is the official YashanDB reserved keywords list.
// Source: SELECT keyword FROM V$RESERVED_WORDS (520 keywords)
var ReservedWordsList = []string{
	// A
	"ABORT", "ACCESS", "ACCOUNT", "ACTIONS", "ADD", "ADMIN", "ADMINISTER", "ALL",
	"ALL_ROWS", "ALTER", "ANALYZE", "AND", "ANY", "APPEND", "APPROX", "APPROXIMATE",
	"ARCHIVE", "ARCHIVELOG", "ARE", "AS", "ASC", "AT", "AUDIT", "AUTHID", "AUTO_LOGIN",
	// B
	"BACKUP", "BASE", "BATCH_MODE", "BEFORE", "BEGIN", "BETWEEN", "BFILE", "BIGFILE",
	"BIGINT", "BINARY", "BINARY_BIGINT", "BINARY_DOUBLE", "BINARY_FLOAT", "BINARY_INTEGER",
	"BINARY_SMALLINT", "BINARY_TINYINT", "BIT", "BITMAP", "BLOB", "BOOLEAN", "BOUND",
	"BUFFER_POOL", "BUILD", "BULK", "BULKLOAD", "BY",
	// C
	"CACHE", "CALL", "CANCEL", "CASCADE", "CASE", "CATEGORY", "CELL_FLASH_CACHE",
	"CHANGE", "CHAR", "CHARACTER", "CHAR_CS", "CHECK", "CHECKPOINT", "CHOOSE", "CHUNK",
	"CLEAN", "CLEAR", "CLOB", "CLOSE", "CLUSTER", "COALESCE", "COLUMN", "COLUMNAR",
	"COLUMNS", "COMMENT", "COMMIT", "COMPAT_MODE", "COMPRESS", "COMPRESSION", "COMPUTE",
	"CONDITION", "CONNECT", "CONNECT_BY_ISCYCLE", "CONNECT_BY_ISLEAF", "CONNECT_BY_ROOT",
	"CONSTRAINT", "CONSTRAINTS", "CONTAINER", "CONTENT", "CONTEXT", "CONTINUE",
	"CONTROLFILES", "CONVERT", "CREATE", "CROSS", "CUBE", "CURRENT", "CURRENT_DATE",
	"CURRENT_TIMESTAMP", "CYCLE",
	// D
	"DATABASE", "DATAFILE", "DATAOID_REUSE", "DATASPACE", "DATE", "DAY", "DEBUG",
	"DECIMAL", "DECLARE", "DECRYPTION", "DEDUPLICATE", "DEFAULT", "DEFINITION",
	"DELETE", "DENSE_RANK", "DESC", "DESTINATION", "DETERMINISTIC", "DICTIONARY",
	"DIRECTORY", "DISABLE", "DISTINCT", "DISTRIBUTE", "DOCUMENT", "DOUBLE",
	"DOUBLE_PRECISION", "DOUBLE_WRITE", "DP_MAX_JOIN_TABLES", "DROP", "DUMP",
	"DUPLICATE", "DUPLICATED",
	// E
	"EDGE", "EDITIONABLE", "ELSE", "ELSIF", "ENABLE", "ENCODING", "ENCRYPT",
	"ENCRYPTION", "END", "ENGINE_COL", "ENGINE_ROW", "EQUIV", "ESCAPE", "EXACT",
	"EXCEPT", "EXCEPTION", "EXCHANGE", "EXEC", "EXECUTE", "EXISTS", "EXIT", "EXPLAIN",
	"EXTEND", "EXTERNAL",
	// F
	"FAILOVER", "FALSE", "FETCH", "FILE_NAME_CONVERT", "FIRST", "FIRST_ROWS",
	"FLASHBACK", "FLASH_CACHE", "FLOAT", "FLOOR", "FLUSH", "FOLLOWING", "FOR", "FORALL",
	"FORCE", "FOREIGN", "FORMAT", "FREELIST", "FREELISTS", "FROM", "FULL", "FUNCTION",
	// G
	"GENERATED", "GLOBAL", "GOTO", "GRANT", "GRAPH", "GRAPH_TABLE", "GROUP", "GROUPING",
	// H
	"HASH_AJ", "HASH_SJ", "HAVING", "HEAP", "HORDER", "HOUR",
	// I
	"IDENTIFIED", "IF", "IGNORE", "IMMEDIATE", "IN", "INCLUDE", "INCREMENT",
	"INCREMENTAL", "INDEPEND", "INDEX", "INDEX_ASC", "INDEX_DESC", "INDEX_FFS",
	"INDEX_JOIN", "INDEX_SS", "INDEX_SS_ASC", "INDEX_SS_DESC", "INITIAL", "INITRANS",
	"INMEMORY", "INNER", "INSERT", "INSTANCE", "INSTANCES", "INT", "INTEGER",
	"INTERSECT", "INTERVAL", "INTO", "INVALIDATE", "INVERTED", "INVISIBLE", "IS",
	// J
	"JOB", "JOIN", "JSON",
	// K
	"KEEP", "KEEP_DUPLICATES", "KEY", "KEYSTORE", "KILL",
	// L
	"LABEL", "LEADING", "LEFT", "LEVEL", "LIBRARY", "LIKE", "LIMIT", "LINK", "LISTENER",
	"LOAD", "LOB", "LOCAL", "LOCK", "LOG", "LOGFILE", "LOGGING", "LOGOFF", "LOGON",
	"LOOP", "LSC",
	// M
	"MANAGE", "MANAGEMENT", "MATCHED", "MATERIALIZED", "MAXDATABUCKETS", "MAXDATAFILES",
	"MAXEXTENTS", "MAXINSTANCES", "MAXLOGFILES", "MAXLOGHISTORY", "MAXSIZE", "MAXTRANS",
	"MAXVALUE", "MAX_WORKERS_PER_EXEC", "MCOL", "MERGE", "MERGE_AJ", "MERGE_SJ",
	"MINEXTENTS", "MINUS", "MINUTE", "MINVALUE", "MOD", "MODIFY", "MONTH", "MOUNT",
	// N
	"NATIONAL", "NATURAL", "NCHAR", "NCHAR_CS", "NCLOB", "NESTED", "NEW", "NEXT",
	"NEXTVAL", "NL_AJ", "NL_SJ", "NO", "NOAPPEND", "NOARCHIVELOG", "NOAUDIT", "NOCACHE",
	"NOCOMPRESS", "NOCYCLE", "NOKEEP", "NOLOGGING", "NOMAXVALUE", "NOMINVALUE",
	"NOMOUNT", "NONEDITIONABLE", "NOORDER", "NOPARALLEL", "NOREVERSE", "NORMAL",
	"NOSCALE", "NOT", "NOVALIDATE", "NOWAIT", "NO_INDEX", "NO_INDEX_FFS", "NO_INDEX_SS",
	"NO_USE_HASH", "NO_USE_MERGE", "NO_USE_NL", "NULL", "NULLS", "NUMBER", "NUMERIC",
	"NVARCHAR", "NVARCHAR2",
	// O
	"OBJECT", "OBJNO_REUSE", "OF", "OFFLINE", "OFFSET", "ON", "ONLINE", "ONLY", "OPEN",
	"OPTIONS", "OR", "ORDER", "ORDERED", "ORGANIZATION", "OUTER", "OUTLINE", "OVER",
	"OVERLAPS",
	// P
	"PACKAGE", "PARALLEL", "PARALLELISM", "PARTITION", "PARTITIONS", "PASSWORD",
	"PCTFREE", "PCTINCREASE", "PCTUSED", "PFILE", "PIPE", "PIVOT", "PLACE_GROUP_BY",
	"PLS_INTEGER", "PLUGGABLE", "PRAGMA", "PRECEDING", "PREPARE", "PRESERVE", "PRIMARY",
	"PRIOR", "PRIVATE", "PRIVILEGE", "PRIVILEGES", "PROCEDURE", "PROFILE", "PROPERTIES",
	"PROPERTY", "PUBLIC", "PURGE",
	// Q
	"QUOTA",
	// R
	"RAISE", "RANGE", "RAW", "READ", "READONLY", "READWRITE", "REAL", "REBUILD",
	"RECLAIM", "RECOVER", "REFERENCES", "REFRESH", "REGISTER", "RELEASE", "RENAME",
	"RESETLOGS", "RESPECT", "RESTART", "RESTORE", "RESTRICT", "RETURN", "RETURNING",
	"REUSE", "REVERSE", "REVOKE", "RIGHT", "RLIKE", "ROLE", "ROLES", "ROLLBACK",
	"ROLLUP", "ROW", "ROWID", "ROWNUM", "ROWS", "RTREE", "RULE",
	// S
	"SAMPLE", "SAVEPOINT", "SCHEDULER", "SCHEMA", "SCN", "SEARCH", "SECOND", "SECTION",
	"SEED", "SEGMENT", "SELECT", "SELECTIVITY", "SEPARATOR", "SEQUENCE", "SESSION",
	"SET", "SETS", "SHARDED", "SHARED", "SHRINK", "SHUTDOWN", "SIBLINGS", "SKIP",
	"SLICE", "SMALLFILE", "SMALLINT", "SOME", "SOURCE", "SPFILE", "SPLIT", "SQL",
	"SQLMAP", "STABLE", "STANDBY", "START", "STATISTICS", "STOP", "STORAGE",
	"SUBPARTITION", "SUBPARTITIONS", "SUBTYPE", "SUCCESSFUL", "SUPPLEMENTAL", "SWAP",
	"SWITCH", "SWITCHOVER", "SYNONYM", "SYSAUX", "SYSDATE", "SYSTEM", "SYSTIMESTAMP",
	"SYS_REFCURSOR",
	// T
	"TABLE", "TABLESPACE", "TAC", "TAG", "TDE", "TEMPFILE", "TEMPORARY", "THEN", "TIME",
	"TIMESTAMP", "TINYINT", "TO", "TRANSACTION", "TRANSPORT", "TRIGGER", "TRUE",
	"TRUNCATE", "TTL", "TYPE",
	// U
	"UNBOUNDED", "UNDO", "UNDO_SEGMENTS", "UNION", "UNIQUE", "UNLOCK", "UNPIVOT",
	"UNUSABLE", "UPDATE", "UPGRADE", "UROWID", "USABLE", "USE", "USE_HASH", "USE_MERGE",
	"USE_NL", "USER", "USING", "UTC_TIMESTAMP",
	// V
	"VALIDATE", "VALUES", "VARCHAR", "VARCHAR2", "VECTOR", "VERTEX", "VIEW", "VISIBLE",
	// W
	"WAIT", "WELLFORMED", "WHEN", "WHENEVER", "WHERE", "WHILE", "WITH", "WITHOUT",
	"WRAPPED",
	// Y
	// Z
	"YEAR", "ZONE", "ZORDER",
}

var ReservedWords = hashset.New(funk.Map(ReservedWordsList, func(s string) interface{} { return s }).([]interface{})...)

func IsReservedWord(v string) bool {
	return ReservedWords.Contains(strings.ToUpper(v))
}

func TryRemoveQuotes(name string) string {
	if len(name) > 1 && name[:1] == "\"" && name[len(name)-1:] == "\"" {
		name = name[1 : len(name)-1]
	}
	return name
}

func TryQuoteReservedWord(name string) string {
	if IsReservedWord(name) {
		return fmt.Sprintf(`"%s"`, name)
	}
	return name
}
